version: "3.8"

services:
  mesh:
    build: .
    restart: always
    container_name: fontend-mesh
    environment:
      - NEXT_PUBLIC_API_URL=http://10.124.1.24:8080
    ports:
      - 5000:3000
    command: pnpm start
